"""feat: adiciona a tabela referente ao email message.

Revision ID: 12cc6fa00a59
Revises: 4504213c01df
Create Date: 2026-10-02 20:30:49.439280

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '12cc6fa00a59'
down_revision = '4504213c01df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('oauth_connections')
    op.drop_table('email_accounts')
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('id', sa.NUMERIC(precision=16), nullable=False),
    sa.Column('user_id', sa.NUMERIC(precision=16), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=240), nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=180), nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=180), nullable=False),
    sa.Column('token_expire_at', sa.DATETIME(), nullable=False),
    sa.Column('scopes', sa.VARCHAR(), nullable=False),
    sa.Column('connected', sa.BOOLEAN(), nullable=False),
    sa.Column('connected_at', sa.DATETIME(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_accounts'))
    )
    op.create_table('oauth_connections',
    sa.Column('id', sa.NUMERIC(precision=16), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.NUMERIC(precision=16), nullable=False),
    sa.Column('code_verifier', sa.VARCHAR(), nullable=False),
    sa.Column('expire_at', sa.DATETIME(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_connections_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_connections'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.NUMERIC(precision=16), nullable=False),
    sa.Column('user_id', sa.NUMERIC(precision=16), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('expire_at', sa.DATETIME(), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
